[project]
name = 'ev-charging-token'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.access]
path = 'contracts/access.clar'
clarity_version = 3
epoch = 'latest'

[contracts.billing]
path = 'contracts/billing.clar'
clarity_version = 3
epoch = '3.2'

[contracts.token]
path = 'contracts/token.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
